version: '3.8'

services:
  # MongoDB for metadata storage
  mongodb:
    image: mongo:7.0
    container_name: rag-vidquest-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: video_rag
    volumes:
      - mongodb_data:/data/db
    networks:
      - rag-network

  # Qdrant for vector storage
  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: rag-vidquest-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag-network

  # Redis for caching and rate limiting
  redis:
    image: redis:7.2-alpine
    container_name: rag-vidquest-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rag-network

  # Ollama for LLM inference
  ollama:
    image: ollama/ollama:latest
    container_name: rag-vidquest-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - rag-network
    # Uncomment if you have NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Main RAG Vidquest application
  rag-vidquest:
    build: .
    container_name: rag-vidquest-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/video_rag?authSource=admin
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_URL=http://ollama:11434/api/chat
      - OLLAMA_MODEL=gemma2:2b
      - SECRET_KEY=your-super-secret-key-change-in-production-32-chars-min
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data:ro
      - ./logs:/app/logs
      - ./metrics:/app/metrics
    depends_on:
      - mongodb
      - qdrant
      - redis
      - ollama
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
  qdrant_data:
  redis_data:
  ollama_data:

networks:
  rag-network:
    driver: bridge
